/process/optical/processActivation Cerenkov  false
/process/optical/processActivation OpWLS  false
/process/optical/processActivation OpWLS2  false
/process/optical/cerenkov/setStackPhotons false


/run/initialize
/vis/open
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate